// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/metrics": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Ingest metrics from agent upload",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "agents"
                ],
                "summary": "Metrics",
                "parameters": [
                    {
                        "description": "Server's metrics",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/agent.MetricMessage"
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "agent.MetricMessage": {
            "type": "object",
            "properties": {
                "@timestamp": {
                    "type": "string"
                },
                "container_name": {
                    "type": "string"
                },
                "cpu": {
                    "type": "object",
                    "properties": {
                        "pressure": {
                            "type": "number"
                        },
                        "throttling": {
                            "type": "number"
                        },
                        "usage": {
                            "type": "number"
                        }
                    }
                },
                "io": {
                    "type": "object",
                    "properties": {
                        "pressure": {
                            "type": "number"
                        },
                        "read_bps": {
                            "type": "number"
                        },
                        "write_bps": {
                            "type": "number"
                        }
                    }
                },
                "memory": {
                    "type": "object",
                    "properties": {
                        "pressure": {
                            "type": "number"
                        },
                        "rss": {
                            "type": "number"
                        },
                        "usage": {
                            "type": "number"
                        },
                        "working_set": {
                            "type": "number"
                        }
                    }
                },
                "oom": {
                    "type": "object",
                    "properties": {
                        "events": {
                            "type": "integer"
                        },
                        "kills": {
                            "type": "integer"
                        }
                    }
                },
                "pids": {
                    "type": "integer"
                },
                "server_id": {
                    "type": "integer"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "description": "API Key for external automated systems.",
            "type": "apiKey",
            "name": "X-Agent-API-Key",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost",
	BasePath:         "/agents",
	Schemes:          []string{},
	Title:            "Agent Service API",
	Description:      "APIs for agents to push data to system",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
