version: "3.8"

services:
  client-server:
    build:
      context: .
      dockerfile: ./cmd/simulation/single_server/Dockerfile
      args:
        CMD_PATH: ./cmd/simulation/single_server/
    ports:
      - "${HOST}:3000:3000"
    labels:
      - monitor=true
    mem_limit: 100m
    cpus: 0.5

  docker-proxy:
    image: tecnativa/docker-socket-proxy
    environment:
      - CONTAINERS=1
      - INFO=1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  monitoring-agent:
    build:
      context: .
      dockerfile: ./cmd/agent/monitoring/docker/Dockerfile
    depends_on:
      - docker-proxy
    environment:
      - SERVER_ID=${CLIENT_AGENT_SERVER_ID}   # TODO: Put this information in API key instead of having to make user adding extra variable themselves
      - API_URL=http://${HOST}:8080/api/v1/agent/metrics 
      - API_KEY=${CLIENT_AGENT_API_KEY}
      - DOCKER_HOST=tcp://docker-proxy:2375
    volumes:
      - /sys/fs/cgroup:/host/sys/fs/cgroup:ro
      - /proc:/host/proc:ro