# Using anchors and aliases to have a common config for multiple services (DRY principle)
x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "50m"
    max-file: "5"

services:
  # Elasticsearch and Kibana setup
  # This current Elasticsearch setup is for local testing only with a single node Elasticsearch cluster, and Kibana dashboard
  # It based on a very minimal setup, with no TLS or HTTPS whatsoever: https://www.elastic.co/docs/deploy-manage/security/set-up-minimal-security
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-wolfi:9.3.1
    restart: always
    env_file:
      - ${ENV_FILE}
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=true
    volumes:
      - es_data:/usr/share/elasticsearch/data
    healthcheck:
      test: ["CMD-SHELL", "curl -s -u ${ELASTIC_USER}:${ELASTIC_PASSWORD} http://localhost:${ELASTIC_PORT}/_cluster/health | grep -q '\"status\"'"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 1m
    logging: *default-logging

  # Run some commands after Elasticsearch cluster is up. Basically check until service is available to take a HTTP request, 
  # then make a request to change password for ES's service account for Kibana
  elasticsearch-setup:
    image: curlimages/curl:latest
    depends_on:
      elasticsearch:
        condition: service_healthy
    entrypoint: ["/bin/sh", "/scripts/elasticsearch/setup.sh"]
    volumes:
      - ./scripts:/scripts
    env_file:
      - ${ENV_FILE}
    restart: no
    logging: *default-logging

  kibana:
    image: docker.elastic.co/kibana/kibana-wolfi:9.3.1
    container_name: kibana
    depends_on:
      elasticsearch:
        condition: service_healthy
      elasticsearch-setup:
        condition: service_completed_successfully
    restart: always
    environment:
      - ELASTICSEARCH_HOSTS=${ELASTIC_HOST}:${ELASTIC_PORT}
      - ELASTICSEARCH_USERNAME=kibana_system
      - ELASTICSEARCH_PASSWORD=${KIBANA_PASSWORD}
    logging: *default-logging
  
  # PostgreSQL DB setup
  postgres:
    image: postgres:latest
    container_name: sqldb
    restart: always
    env_file:
      - ${ENV_FILE}
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -h localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    logging: *default-logging

  # Postgres schema migration
  postgres-migrate:
    image: migrate/migrate
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./migrations:/migrations
    env_file:
      - ${ENV_FILE}
    command: [
      "-path", "/migrations",
      "-database", "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:${POSTGRES_PORT}/${POSTGRES_DB}?sslmode=disable",
      "up"
    ]
    logging: *default-logging
  
  # Redis setup
  redis:
    image: redis/redis-stack:latest
    container_name: redis
    restart: always
    env_file:
      - ${ENV_FILE}
    environment:
      - REDIS_ARGS=--requirepass ${REDIS_PASSWORD}
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD-SHELL", "redis-cli -a ${REDIS_PASSWORD} ping | grep PONG"]
      interval: 10s
      timeout: 5s
      retries: 5
    logging: *default-logging

  kafka:
    image: apache/kafka:latest
    container_name: kafka
    restart: always
    environment:
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_NODE_ID: 1

      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      
      KAFKA_LISTENERS: PLAINTEXT://:9092,EXTERNAL://:29092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,EXTERNAL://${HOST}:29092
      
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      
      KAFKA_LOG_DIRS: /var/lib/kafka/data
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1   # Since there's only 1 broker, Kafka can't replicate a partition more than 1
    volumes:
      - kafka_data:/var/lib/kafka/data

  kafka-ui:
    image: docker.redpanda.com/redpandadata/console:latest
    container_name: redpanda-kafka-ui
    restart: always
    depends_on:
      - kafka
    environment:
      KAFKA_BROKERS: kafka:9092

  kafka-setup:
    image: apache/kafka:latest
    depends_on:
      kafka:
        condition: service_started
    entrypoint: ["/bin/sh", "/scripts/kafka/setup.sh"]
    volumes:
      - ./scripts:/scripts
    env_file:
      - ${ENV_FILE}
    restart: "no"
    logging: *default-logging
  
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"   # API
      - "9001:9001"   # Console UI
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    restart: unless-stopped
  
  minio-init:
    image: minio/mc
    depends_on:
      - minio
    env_file:
      - ${ENV_FILE}
    entrypoint: ["/bin/sh", "/scripts/minio/setup.sh"]
    volumes:
      - ./scripts:/scripts

volumes:
  es_data:
  postgres_data:
  redis_data:
  kafka_data:
  minio_data: