services:
  postgres:
    ports:
      - "${HOST}:5432:5432"

  redis:
    ports:
      - "${HOST}:6379:6379"
      - "${HOST}:8001:8001"

  elasticsearch:
    ports:
      - "${HOST}:9200:9200"
  
  kibana:
    ports:
      - "${HOST}:5601:5601"
  
  kafka:
    ports:
      - "${HOST}:9092:9092"
      - "${HOST}:29092:29092"
  
  kafka-ui:
    ports:
      - "${HOST}:8081:8080"
  
  auth-service:
    ports:
      - "${HOST}:8087:8087"
  
  users-service:
    ports:
      - "${HOST}:8082:8082"
  
  servers-service:
    ports:
      - "${HOST}:8083:8083"
  
  monitoring-service:
    ports:
      - "${HOST}:8084:8084"

  agents-service:
    ports:
      - "${HOST}:8085:8085"

  jobs-service:
    ports:
      - "${HOST}:8086:8086"
  
  traefik:
    ports:
      - "${HOST}:8088:8080" # Traefik dashboard

  simulation:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        CMD_PATH: ./cmd/simulation/multi_servers
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - ${ENV_FILE}
    environment:
      - APP_ENV=docker
    networks:
      - app-network

networks:
  app-network:
    driver: bridge