services:
  client-server:
    build:
      context: .
      dockerfile: ./cmd/simulation/single_server/Dockerfile
      args:
        CMD_PATH: ./cmd/simulation/single_server/
    ports:
      - "${HOST}:3001:3001"
    labels:
      - monitor=true
    mem_limit: 100m
    cpus: 0.5

  docker-proxy:
    image: tecnativa/docker-socket-proxy
    environment:
      - CONTAINERS=1
      - INFO=1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  monitoring-agent:
    build:
      context: ./agents/monitoring/docker/
      dockerfile: Dockerfile
    depends_on:
      - docker-proxy
    environment:
      - SERVER_NAME=${SERVER_NAME}   # TODO: Put this information in API key instead of having to make user adding extra variable themselves
      - API_URL=http://${HOST}
      - DOCKER_HOST=tcp://docker-proxy:2375

      - EMAIL=${EMAIL}
      - PASSWORD=${PASSWORD}
    volumes:
      - /sys/fs/cgroup:/host/sys/fs/cgroup:ro
      - /proc:/host/proc:ro
      - agent-data:/app/data
      - /etc/machine-id:/host/machine-id:ro

volumes:
  agent-data: