# Using anchors and aliases to have a common config for multiple services (DRY principle)
x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "50m"
    max-file: "5"

x-common-dependency: &common-dependency
  postgres:
    condition: service_healthy
  redis:
    condition: service_healthy
  elasticsearch:
    condition: service_healthy
  kafka:
    condition: service_started
  postgres-migrate:
    condition: service_completed_successfully
  kafka-setup:
    condition: service_completed_successfully

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        CMD_PATH: ./cmd/api
    ports:
      - "${HOST}:8080:8080"
    restart: unless-stopped
    depends_on: *common-dependency
    env_file:
      - ${ENV_FILE}
    environment:
      - APP_ENV=docker
    logging: *default-logging

  servers_checker:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        CMD_PATH: ./cmd/worker/servers_checker
    restart: unless-stopped
    depends_on: *common-dependency
    env_file:
      - ${ENV_FILE}
    environment:
      - APP_ENV=docker
    logging: *default-logging
  
  cron_scheduler:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        CMD_PATH: ./cmd/worker/cron_scheduler
    restart: unless-stopped
    depends_on: *common-dependency
    env_file:
      - ${ENV_FILE}
    environment:
      - APP_ENV=docker
    logging: *default-logging

  metrics_consumer:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        CMD_PATH: ./cmd/worker/metrics_consumer
    restart: unless-stopped
    depends_on: *common-dependency
    env_file:
      - ${ENV_FILE}
    environment:
      - APP_ENV=docker
    logging: *default-logging
  
  file_importer_consumer:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        CMD_PATH: ./cmd/worker/file_importer_consumer
    restart: unless-stopped
    depends_on: *common-dependency
    env_file:
      - ${ENV_FILE}
    environment:
      - APP_ENV=docker
    logging: *default-logging