version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        CMD_PATH: ./cmd/api
    ports:
      - "8080:8080"
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

      - REDIS_HOST=redis
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}

      - ELASTIC_HOST=http://elasticsearch
      - ELASTIC_PORT=9200
      - ELASTIC_USER=${ELASTIC_USER}
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}

      - MAIL_SERVER=${MAIL_SERVER}
      - MAIL_PORT=${MAIL_PORT}
      - MAIL_USER=${MAIL_USER}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - MAIL_FROM_USER=${MAIL_FROM_USER}

      - JWT_SECRET=${JWT_SECRET}

  servers_checker:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        CMD_PATH: ./cmd/worker/servers_checker
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

      - REDIS_HOST=redis
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}

      - ELASTIC_HOST=http://elasticsearch
      - ELASTIC_PORT=9200
      - ELASTIC_USER=${ELASTIC_USER}
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}

      - MAIL_SERVER=${MAIL_SERVER}
      - MAIL_PORT=${MAIL_PORT}
      - MAIL_USER=${MAIL_USER}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - MAIL_FROM_USER=${MAIL_FROM_USER}

      - JWT_SECRET=${JWT_SECRET}
  
  emailer:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        CMD_PATH: ./cmd/worker/emailer
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

      - REDIS_HOST=redis
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}

      - ELASTIC_HOST=http://elasticsearch
      - ELASTIC_PORT=9200
      - ELASTIC_USER=${ELASTIC_USER}
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}

      - MAIL_SERVER=${MAIL_SERVER}
      - MAIL_PORT=${MAIL_PORT}
      - MAIL_USER=${MAIL_USER}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - MAIL_FROM_USER=${MAIL_FROM_USER}

      - JWT_SECRET=${JWT_SECRET}

  # Elasticsearch and Kibana setup
  # This current Elasticsearch setup is for local testing only with a single node Elasticsearch cluster, and Kibana dashboard
  # It based on a very minimal setup, with no TLS or HTTPS whatsoever: https://www.elastic.co/docs/deploy-manage/security/set-up-minimal-security
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-wolfi:9.3.1
    container_name: es01
    restart: always
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - xpack.security.enabled=true
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    healthcheck:
      test: ["CMD-SHELL", "curl -s -u ${ELASTIC_USER}:${ELASTIC_PASSWORD} ${ELASTIC_HOST}:${ELASTIC_PORT} >/dev/null || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 1m

  # Run some commands after Elasticsearch cluster is up. Basically check until service is available to take a HTTP request, 
  # then make a request to change password for ES's service account for Kibana
  elasticsearch-setup:
    image: curlimages/curl:latest
    depends_on:
      elasticsearch:
        condition: service_healthy
    entrypoint: ["/bin/sh", "/scripts/elasticsearch/setup.sh"]
    volumes:
      - ./scripts:/scripts
    environment:
      - ELASTIC_USER=${ELASTIC_USER}
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - KIBANA_PASSWORD=${KIBANA_PASSWORD}
    restart: no

  kibana:
    image: docker.elastic.co/kibana/kibana-wolfi:9.3.1
    container_name: kibana
    depends_on:
      elasticsearch:
        condition: service_healthy
      elasticsearch-setup:
        condition: service_completed_successfully
    restart: always
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=kibana_system
      - ELASTICSEARCH_PASSWORD=${KIBANA_PASSWORD}
    ports:
      - "5601:5601"
  
  # PostgreSQL DB setup
  postgres:
    image: postgres:latest
    container_name: sqldb
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Postgres schema migration
  migrate:
    image: migrate/migrate
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./migrations:/migrations
    command: [
      "-path", "/migrations",
      "-database", "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}?sslmode=disable",
      "up"
    ]
  
  # Redis setup
  redis:
    image: redis/redis-stack:latest
    container_name: redis
    restart: always
    environment:
      - REDIS_ARGS=--requirepass ${REDIS_PASSWORD}
    ports:
      - "6379:6379"
      - "8001:8001"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  es_data:
  postgres_data:
  redis_data: