# Using anchors and aliases to have a common config for multiple services (DRY principle)
x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "50m"
    max-file: "5"

x-service-defaults: &service-defaults
  restart: unless-stopped
  env_file:
    - .env.docker
  environment:
    - APP_ENV=docker
  logging: *default-logging
  networks:
    - app-network

services:
  auth-service:
    <<: *service-defaults
    build:
      context: ./services/auth-service
      dockerfile: Dockerfile
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.auth.rule=PathPrefix(`/auth`)"
      - "traefik.http.services.auth.loadbalancer.server.port=8087"
      - "traefik.http.middlewares.auth-strip.stripprefix.prefixes=/auth"
      - "traefik.http.routers.auth.middlewares=auth-strip"
      - "traefik.docker.network=app-network"
    depends_on:
      postgres-migrate:
        condition: service_completed_successfully
      redis:
        condition: service_healthy
    
    # For Swarm mode later
    # image: server-management-system-auth-service:latest 
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure

  users-service:
    <<: *service-defaults
    build:
      context: ./services/users-service
      dockerfile: Dockerfile
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.user.rule=PathPrefix(`/users`)"
      - "traefik.http.services.user.loadbalancer.server.port=8082"
      - "traefik.http.middlewares.user-strip.stripprefix.prefixes=/users"
      - "traefik.http.routers.user.middlewares=user-strip"
      - "traefik.docker.network=app-network"
    depends_on:
      postgres-migrate:
        condition: service_completed_successfully

    # For Swarm mode later
    # image: server-management-system-user-service:latest 
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure

  servers-service:
    <<: *service-defaults
    build:
      context: ./services/servers-service
      dockerfile: Dockerfile
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.servers.rule=PathPrefix(`/servers`)"
      - "traefik.http.services.servers.loadbalancer.server.port=8083"
      - "traefik.http.middlewares.servers-strip.stripprefix.prefixes=/servers"
      - "traefik.http.routers.servers.middlewares=servers-strip"
      - "traefik.docker.network=app-network"
    depends_on:
      postgres-migrate:
        condition: service_completed_successfully
      elasticsearch-setup:
        condition: service_completed_successfully

    # For Swarm mode later
    # image: server-management-system-server-service:latest
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure

  monitoring-service:
    <<: *service-defaults
    build:
      context: ./services/monitoring-service
      dockerfile: Dockerfile
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.monitoring.rule=PathPrefix(`/monitoring`)"
      - "traefik.http.services.monitoring.loadbalancer.server.port=8084"
      - "traefik.http.middlewares.monitoring-strip.stripprefix.prefixes=/monitoring"
      - "traefik.http.routers.monitoring.middlewares=monitoring-strip"
      - "traefik.docker.network=app-network"
    depends_on:
      postgres-migrate:
        condition: service_completed_successfully
      elasticsearch-setup:
        condition: service_completed_successfully

    # For Swarm mode later
    # image: server-management-system-monitoring-service:latest
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure

  agents-service:
    <<: *service-defaults
    build:
      context: ./services/agents-service
      dockerfile: Dockerfile
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.agent.rule=PathPrefix(`/agent`)"
      - "traefik.http.services.agent.loadbalancer.server.port=8085"
      - "traefik.http.middlewares.agent-strip.stripprefix.prefixes=/agent"
      - "traefik.http.routers.agent.middlewares=agent-strip"
      - "traefik.docker.network=app-network"
    depends_on:
      postgres-migrate:
        condition: service_completed_successfully
      kafka-setup:
        condition: service_completed_successfully
    
    # For Swarm mode later
    # image: server-management-system-agent-service:latest
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure

  jobs-service:
    <<: *service-defaults
    build:
      context: ./services/jobs-service
      dockerfile: Dockerfile
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jobs.rule=PathPrefix(`/jobs`)"
      - "traefik.http.services.jobs.loadbalancer.server.port=8086"
      - "traefik.http.middlewares.jobs-strip.stripprefix.prefixes=/jobs"
      - "traefik.http.routers.jobs.middlewares=jobs-strip"
      - "traefik.docker.network=app-network"
    depends_on:
      postgres-migrate:
        condition: service_completed_successfully
      kafka-setup:
        condition: service_completed_successfully
      minio-init:
        condition: service_completed_successfully
    
    # For Swarm mode later
    # image: server-management-system-jobs-service:latest
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure

  traefik:
    image: traefik:latest
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      # - "--providers.docker.swarmMode=true"
      - "--providers.docker.endpoint=unix:///var/run/docker.sock"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - app-network
    deploy:
      placement:
        constraints:
          - node.role == manager

  metrics-consumer:
    <<: *service-defaults
    build:
      context: ./workers/metrics-consumer
      dockerfile: Dockerfile
    depends_on:
      kafka-setup:
        condition: service_completed_successfully
      elasticsearch-setup:
        condition: service_completed_successfully

    # For Swarm mode later
    # image: server-management-system-metrics-consumer:latest
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
  
  files-import-consumer:
    <<: *service-defaults
    build:
      context: ./workers/files-import-consumer
      dockerfile: Dockerfile
    depends_on:
      postgres-migrate:
        condition: service_completed_successfully
      kafka-setup:
        condition: service_completed_successfully
      minio-init:
        condition: service_completed_successfully

    # For Swarm mode later
    # image: server-management-files-import-consumer:latest
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
  
  servers-ping-checker:
    <<: *service-defaults
    build:
      context: ./workers/servers-ping-checker
      dockerfile: Dockerfile
    depends_on:
      postgres-migrate:
        condition: service_completed_successfully
      elasticsearch-setup:
        condition: service_completed_successfully

    # For Swarm mode later
    # image: server-management-servers-ping-checker:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
  
  cron-scheduler:
    <<: *service-defaults
    build:
      context: ./workers/cron-scheduler
      dockerfile: Dockerfile
    depends_on:
      postgres-migrate:
        condition: service_completed_successfully
      elasticsearch-setup:
        condition: service_completed_successfully
      minio-init:
        condition: service_completed_successfully

    # For Swarm mode later
    # image: server-management-system-cron-scheduler:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

networks:
  app-network:
    driver: bridge