import { useState, type FormEvent } from "react";
import { useNavigate } from "react-router-dom";
import { useAuth } from "../contexts/auth";

export default function Login() {
  const { login } = useAuth(); const navigate = useNavigate(); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [error, setError] = useState(""); const [pending, setPending] = useState(false);
  const submit = async (event: FormEvent) => { event.preventDefault(); setPending(true); setError(""); try { await login(email, password); navigate("/servers"); } catch { setError("We couldn't sign you in. Check your email and password."); } finally { setPending(false); } };
  return <div className="login-page"><section className="login-aside"><NavArt /><div><span className="eyebrow">SMS-X / OPERATIONS PLATFORM</span><h1>Know your fleet<br />at a glance.</h1><p>One focused control center for the servers your teams depend on.</p></div><div className="login-pulse"><i /> <span>Monitoring services are online</span></div></section><main className="login-main"><form className="login-card" onSubmit={submit}><div className="mobile-brand"><span className="brand-mark">S</span> SMS<span className="brand-accent">-X</span></div><div><span className="eyebrow">WELCOME BACK</span><h2>Sign in to your workspace</h2><p className="muted">Use your organization account to continue.</p></div>{error && <div className="error-message">{error}</div>}<label>EMAIL ADDRESS<input type="email" autoComplete="email" placeholder="you@company.com" value={email} onChange={(e) => setEmail(e.target.value)} required /></label><label>PASSWORD<input type="password" autoComplete="current-password" placeholder="Enter your password" value={password} onChange={(e) => setPassword(e.target.value)} required /></label><button className="primary-button full" disabled={pending}>{pending ? "Signing in…" : "Sign in"}<span>→</span></button><p className="form-footnote">Your session renews securely while you work.</p></form></main></div>;
}
function NavArt() { return <div className="grid-art" aria-hidden="true"><span /><span /><span /><span /><span /><span /><span /><span /><b /></div>; }
