import { useCallback, useEffect, useState } from "react";
import { Link } from "react-router-dom";
import api from "../api/client";
import type { Server, ServerListResponse } from "../types/api";

const normalize = (data: Server[] | ServerListResponse) => Array.isArray(data) ? { servers: data, total: data.length } : { servers: data.servers ?? [], total: data.total ?? data.servers?.length ?? 0 };
export default function Servers() {
  const [servers, setServers] = useState<Server[]>([]); const [query, setQuery] = useState(""); const [page, setPage] = useState(1); const [total, setTotal] = useState(0); const [loading, setLoading] = useState(true); const [loadError, setLoadError] = useState(""); const [showCreate, setShowCreate] = useState(false); const pageSize = 10;
  const load = useCallback(async () => { setLoading(true); setLoadError(""); try { const { data } = await api.get<Server[] | ServerListResponse>("/servers", { params: { name: query || undefined, page, page_size: pageSize, sort_by: "created_at", order: "desc" } }); const result = normalize(data); setServers(result.servers); setTotal(result.total); } catch { setLoadError("Unable to load your fleet. Check that the servers service is running and your session is valid."); } finally { setLoading(false); } }, [query, page]);
  useEffect(() => { const timer = window.setTimeout(load, 180); return () => clearTimeout(timer); }, [load]);
  const download = async () => { const { data } = await api.get("/servers/export", { params: { name: query || undefined }, responseType: "blob" }); const url = URL.createObjectURL(data); const a = document.createElement("a"); a.href = url; a.download = "servers.csv"; a.click(); URL.revokeObjectURL(url); };
  const pageCount = Math.max(1, Math.ceil(total / pageSize)); const up = servers.filter((server) => server.status === "UP").length;
  return <><section className="stat-row"><Stat label="Visible servers" value={total} note="In your current view" /><Stat label="Operational" value={up} note="Reporting UP status" tone="good" /><Stat label="Attention needed" value={servers.filter((server) => server.status !== "UP").length} note="Down or awaiting data" tone="warm" /></section><section className="panel fleet-panel"><div className="panel-heading"><div><h2>Your fleet</h2><p>Search, manage, and inspect your monitored endpoints.</p></div><div className="actions"><button className="secondary-button" onClick={download}>↓ Export CSV</button><button className="primary-button" onClick={() => setShowCreate(true)}>+ Add server</button></div></div>{loadError && <div className="error-message">{loadError}</div>}<div className="table-tools"><label className="search-field"><span>⌕</span><input value={query} onChange={(e) => { setQuery(e.target.value); setPage(1); }} placeholder="Search by server name…" /></label><span className="result-count">{total} total servers</span></div><div className="table-wrap"><table><thead><tr><th>SERVER</th><th>ADDRESS</th><th>STATUS</th><th>LAST UPDATED</th><th /></tr></thead><tbody>{loading ? <tr><td colSpan={5} className="empty-cell">Loading fleet data…</td></tr> : servers.length === 0 ? <tr><td colSpan={5} className="empty-cell">No servers match this search.</td></tr> : servers.map((server) => <tr key={server.id}><td><Link className="server-name" to={`/servers/${server.id}`}>{server.name}</Link><small>ID {server.id}</small></td><td className="mono">{server.ipv4}</td><td><Status status={server.status} /></td><td>{new Date(server.updated_at).toLocaleString()}</td><td><Link className="row-link" to={`/servers/${server.id}`}>View →</Link></td></tr>)}</tbody></table></div><footer className="table-footer"><span>Page {page} of {pageCount}</span><div><button className="page-button" disabled={page === 1} onClick={() => setPage(page - 1)}>← Previous</button><button className="page-button" disabled={page >= pageCount} onClick={() => setPage(page + 1)}>Next →</button></div></footer></section>{showCreate && <CreateServer onClose={() => setShowCreate(false)} onCreated={(created) => { setServers((current) => [created, ...current]); setTotal((current) => current + 1); setShowCreate(false); void load(); }} />}</>;
}
export function Status({ status }: { status: string }) { const normalized = status === "UP" ? "up" : status === "DOWN" ? "down" : "neutral"; return <span className={`status ${normalized}`}><i />{status.replace("_", " ")}</span>; }
function Stat({ label, value, note, tone = "" }: { label: string; value: number; note: string; tone?: string }) { return <div className={`stat-card ${tone}`}><span>{label}</span><strong>{value.toLocaleString()}</strong><small>{note}</small></div>; }
function CreateServer({ onClose, onCreated }: { onClose(): void; onCreated(server: Server): void }) { const [name, setName] = useState(""); const [ipv4, setIpv4] = useState(""); const [error, setError] = useState(""); const [pending, setPending] = useState(false); const submit = async (e: React.FormEvent) => { e.preventDefault(); setPending(true); setError(""); try { const { data } = await api.post<Server>("/servers/", { name, ipv4 }); onCreated({ ...data, status: data.status ?? "NO_DATA" }); } catch { setError("Server could not be created. Confirm the server name and IPv4 address."); } finally { setPending(false); } }; return <div className="modal-backdrop"><form className="modal" onSubmit={submit}><button className="close-button" type="button" onClick={onClose}>×</button><span className="eyebrow">NEW ENDPOINT</span><h2>Add a server</h2><p className="muted">This server will belong to your account.</p>{error && <div className="error-message">{error}</div>}<label>SERVER NAME<input value={name} onChange={(e) => setName(e.target.value)} placeholder="e.g. api-production-01" required /></label><label>IPV4 ADDRESS<input value={ipv4} onChange={(e) => setIpv4(e.target.value)} placeholder="e.g. 10.0.10.24" required /></label><div className="modal-actions"><button type="button" className="secondary-button" onClick={onClose}>Cancel</button><button className="primary-button" disabled={pending}>{pending ? "Adding…" : "Add server"}</button></div></form></div>; }
